services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80" 
    volumes: 
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf 
    restart: always  
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      - db
      - phpmyadmin

  frontend:
    image: node:18-alpine 
    platform: linux/amd64
    container_name: react
    working_dir: /usr/src/app
    volumes:
      - ./Frontend:/usr/src/app
    ports:
      - "5173:5173"  
    command: ["sh", "-c", "npm install vite --save-dev && npm start -- --host"]
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    image: node:18-alpine 
    platform: linux/amd64
    container_name: express
    working_dir: /usr/src/app
    volumes:
      - ./Backend:/usr/src/app
    ports:
      - "4500:4500"  # API server
    command: ["sh", "-c", "npm install && node server.js"]
    environment:
      - NODE_ENV=development
      - PORT=4500
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=elearning
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0 
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin 
    platform: linux/amd64
    container_name: phpmyadmin 
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "200:80"
    depends_on:
      - db
    links:
      - db
    networks:
      - app-network

volumes:
  mysql-data: 


networks:
  app-network:
    driver: bridge